# Change these first
owner: dlt-web
repo: status

# Add your sites here
sites:
  - name: Blackboard
    url: https://vle.shef.ac.uk
  - name: Turnitin
    url: https://turnitinuk.com/login_page.asp
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Test for HEAD
    method: HEAD
    url: https://www.google.com
  - name: Secret Site
    url: $SECRET_SITE
  - name: TCP ping
    url: 1.1.1.1

status-website:
  # customHeadHtml: "<!-- Custom HTML to add in the <head> tag -->"
  # customBodyHtml: "<div class="svelte-14gfn20">More Information</div>"
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: #enter cname here
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status 
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Digital Learning Status Page** automatically updated every 5 minutes"
  introMessage: This page lists the availability of Digital Learning Tools at the University of Sheffield. **This page is in beta** and is powered by an open source [GitHub repository](https://github.com/upptime/upptime). 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
